### ISSUE TITLE
Permissions Error on Windows

### ISSUE THREAD

**Issue by KR0SIV** [KYDronePilot/hdfm#15]
I'm having a permission error when attempting to run this on Windows 7 in an administrative cmd prompt.

`C:\Users\Harold\Downloads\hdfm-master\hdfm-master>Traceback (most recent call la
st):
  File "<string>", line 1, in <module>
  File "C:\Users\Harold\AppData\Local\Programs\Python\Python37-32\lib\multiproce
ssing\spawn.py", line 99, in spawn_main
    new_handle = reduction.steal_handle(parent_pid, pipe_handle)
  File "C:\Users\Harold\AppData\Local\Programs\Python\Python37-32\lib\multiproce
ssing\reduction.py", line 87, in steal_handle
    _winapi.DUPLICATE_SAME_ACCESS | _winapi.DUPLICATE_CLOSE_SOURCE)
PermissionError: [WinError 5] Access is denied
`

I have the nrsc5.exe and it's libnrsc5.dll application extension in the same folder and have checked that I have permissions. Not sure why I'm getting this error.

**Comment by KYDronePilot** [comment]
I've done some research on the problem and it looks like it has something to do with the `subprocess` module not playing well with Windows. When I developed the program, I only tested it on Mac and Linux, for lack of a Windows machine that I could get NRSC5 running on.

I plan on doing another refactoring of the code around December this year (maybe earlier if I can spare the time). My goal is to make a bundled version that doesn't require Python or anything else to be installed to run the program. At that time I will also test it on Windows and make sure everything is working.

If you would really like to try it in the mean time, I would recommend running it on a Raspberry Pi (if accessible) or live booting your Windows machine to Linux and temporarily trying to run everything.

**Comment by huseman21** [comment]
When I try to run it in windows 10 I get these errors;

Traceback (most recent call last):
  File "hdfm.py", line 7, in <module>
    import src.gui
  File "D:\software radio\HD digital radio\src\gui.py", line 1, in <module>
    import multiprocessing
  File "C:\Users\huseman\AppData\Local\Programs\Python\Python38\lib\multiprocessing\__init__.py", line 16, in <module>
    from . import context
  File "C:\Users\huseman\AppData\Local\Programs\Python\Python38\lib\multiprocessing\context.py", line 6, in <module>
    from . import reduction
  File "C:\Users\huseman\AppData\Local\Programs\Python\Python38\lib\multiprocessing\reduction.py", line 16, in <module>
    import socket
  File "C:\Users\huseman\AppData\Local\Programs\Python\Python38\lib\socket.py", line 49, in <module>
    import _socket
ImportError: DLL load failed while importing _socket: %1 is not a valid Win32 application.

**Comment by huseman21** [comment]
I gave it a shot, ran into the same issue.

I'm using python 3.9.1 32bit in windows 10.

When I launch your python code it does start the radio station playing and populates the dump folder with the images so thats great.  However;  Python spits out errors and the nrsc5.exe file continues to run in the background even after exiting out of python, so it has to be manually stopped with task manager to be able to relaunch your code or change the channel.  Also the nrsc5.exe does not display any window.  Any ideas on how to fix this?  I have tried running as administrator but it has the same issue.



D:\software radio\HD digital radio\hdfm-master>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files (x86)\Python39-32\lib\multiprocessing\spawn.py", line 107, in spawn_main
    new_handle = reduction.duplicate(pipe_handle,
  File "C:\Program Files (x86)\Python39-32\lib\multiprocessing\reduction.py", line 79, in duplicate
    return _winapi.DuplicateHandle(
PermissionError: [WinError 5] Access is denied

**Comment by KYDronePilot** [comment]
@KR0SIV and @huseman21 Try installing the latest release: https://github.com/KYDronePilot/hdfm/releases/latest. I've completely rewritten the program as a standalone Rust binary so these issues should be gone.
